module GitHub.Encode exposing (..)

{-| Generated by elm-json-interop.
-}

import GitHub exposing (..)
import Json.Encode as E
import Utils.Json.Encode_ as E_ exposing (Encoder)


response : Encoder Response
response =
    \v1 ->
        E.object
            [ ( "data"
              , (\v2 ->
                    E.object
                        [ ( "viewer"
                          , (\v3 ->
                                E.object
                                    [ ( "repositories"
                                      , (\v4 ->
                                            E.object
                                                [ ( "nodes"
                                                  , E.list repository v4.nodes
                                                  )
                                                ]
                                        )
                                            v3.repositories
                                      )
                                    ]
                            )
                                v2.viewer
                          )
                        ]
                )
                    v1.data
              )
            ]


repository : Encoder Repository
repository =
    \v1 ->
        E.object
            [ ( "name"
              , E.string v1.name
              )
            , ( "description"
              , E_.maybe E.string v1.description
              )
            , ( "url"
              , E.string v1.url
              )
            , ( "homepageUrl"
              , E_.maybe E.string v1.homepageUrl
              )
            , ( "repositoryTopics"
              , (\v2 ->
                    E.object
                        [ ( "nodes"
                          , E.list
                                (\v3 ->
                                    E.object
                                        [ ( "topic"
                                          , (\v4 ->
                                                E.object
                                                    [ ( "name"
                                                      , E.string v4.name
                                                      )
                                                    ]
                                            )
                                                v3.topic
                                          )
                                        ]
                                )
                                v2.nodes
                          )
                        ]
                )
                    v1.repositoryTopics
              )
            ]
